/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.taobao.view;

import com.taobao.controller.LintScanner;
import static com.taobao.controller.LintScanner.executeCmdCommand;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.FutureTask;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wb-maohongyun
 */
public class Panel2 extends javax.swing.JPanel {

    /**
     * Creates new form Panel2
     */
    public Panel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("删除重复资源");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("删除未使用资源");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (Panel1.projectDir == null || !Panel1.projectDir.exists()) {
            //Warning user!!!
            Panel1.projectDir = new File(LintScanner.PROJECT_HOME);
//            return;
        }
        if (Panel1.lintDir == null || !Panel1.lintDir.exists()) {
            //Warning user!!!
            Panel1.lintDir = new File(LintScanner.LINT_HOME);
//            return;
        }
        File resultTmpFile = new File(Panel1.projectDir, "lint_result.xml");
        if (!resultTmpFile.exists()) {
            try {
                resultTmpFile.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Panel2.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
        }
        FutureTask<String> t = executeCmdCommand(
                "cmd /c " + Panel1.lintDir.getAbsolutePath() + File.pathSeparator
                + "lint " + Panel1.projectDir.getAbsolutePath() + " --check UnusedResources,IconDuplicates,IconDuplicatesConfig --xml "
                + resultTmpFile.getAbsolutePath()
        );
        try {
            if (t.get().equals("success")) {
                System.out.println("!!!!!!!!!!!!!!!!!!!! sucessful!");
                LintScanner.deleteUnusedResources(LintScanner.parseXMLUseJDOM());
            }
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
